<a href="https://colab.research.google.com/github/hcroyalcore-lgtm/Nauka-o-danych/blob/main/nauka_o_danych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

dane = {
    "Klient": ["Anna", "Bartek", "Celina", "Dawid", "Ewa"],
    "Miasto": ["Warszawa", "Kraków", "Warszawa", "Gdańsk", "Kraków"],
    "Wiek": [28, 34, 22, 45, 29],
    "Kwota_zakupu": [120.50, 450.00, 89.90, 310.20, 215.00],
    "Status_VIP": [False, True, False, True, False],
}

df = pd.DataFrame(dane)
print(df)

   Klient    Miasto  Wiek  Kwota_zakupu  Status_VIP
0    Anna  Warszawa    28         120.5       False
1  Bartek    Kraków    34         450.0        True
2  Celina  Warszawa    22          89.9       False
3   Dawid    Gdańsk    45         310.2        True
4     Ewa    Kraków    29         215.0       False

In [ ]:
df.groupby("Status_VIP").agg({"Wiek": "mean", "Kwota_zakupu": "sum"})

                 Wiek  Kwota_zakupu
Status_VIP
False       26.333333         425.4
True        39.500000         760.2

In [ ]:
srednia_na_miasto = df.groupby("Miasto")["Kwota_zakupu"].mean()
display(srednia_na_miasto)

Miasto
Gdańsk      310.2
Kraków      332.5
Warszawa    105.2
Name: Kwota_zakupu, dtype: float64

In [ ]:
df.groupby("Status_VIP").agg({"Wiek": "mean", "Kwota_zakupu": "sum"})

                 Wiek  Kwota_zakupu
Status_VIP
False       26.333333         425.4
True        39.500000         760.2

In [ ]:
df.groupby("Miasto")["Kwota_zakupu"].agg(["mean", "count"])

           mean  count
Miasto
Gdańsk    310.2      1
Kraków    332.5      2
Warszawa  105.2      2

In [ ]:
df.groupby("Miasto")["Kwota_zakupu"].agg(["mean", "count", "max"])

           mean  count    max
Miasto
Gdańsk    310.2      1  310.2
Kraków    332.5      2  450.0
Warszawa  105.2      2  120.5

In [ ]:
df.groupby("Miasto")["Kwota_zakupu"].agg([
    "mean",
    "count",
    "max",
    ("roznica_max_min", lambda x: x.max() - x.min())
])

           mean  count    max  roznica_max_min
Miasto
Gdańsk    310.2      1  310.2              0.0
Kraków    332.5      2  450.0            235.0
Warszawa  105.2      2  120.5             30.6

In [ ]:
# 1. Procentowy udział klientów VIP w każdym mieście
udzial_vip = df.groupby("Miasto")["Status_VIP"].agg([
    ("procent_VIP", lambda x: (x.sum() / len(x)) * 100)
])
print("1. Procent VIP-ów w miastach:")
display(udzial_vip)

# 2. Specyficzne kwantyle (np. 90. percentyl kwoty zakupu)
percentyl_90 = df.groupby("Miasto")["Kwota_zakupu"].agg([
    ("90_percentyl", lambda x: x.quantile(0.9))
])
print("\n2. 90. percentyl kwoty zakupów:")
display(percentyl_90)

# 3. Zliczanie unikalnych wartości (odpowiednik SQL: COUNT DISTINCT)
unikalne_zakupy = df.groupby("Miasto")["Kwota_zakupu"].agg([
    ("liczba_unikalnych_kwot", lambda x: x.nunique())
])
print("\n3. Liczba unikalnych kwot zakupów:")
display(unikalne_zakupy)

1. Procent VIP-ów w miastach:

          procent_VIP
Miasto
Gdańsk          100.0
Kraków           50.0
Warszawa          0.0

2. 90. percentyl kwoty zakupów:

          90_percentyl
Miasto
Gdańsk          310.20
Kraków          426.50
Warszawa        117.44

3. Liczba unikalnych kwot zakupów:

          liczba_unikalnych_kwot
Miasto
Gdańsk                         1
Kraków                         2
Warszawa                       2

In [ ]:
udzial_vip.T

Miasto       Gdańsk  Kraków  Warszawa
procent_VIP   100.0    50.0       0.0